* Interleave adapted to org-ref and helm-bibtex

You can find an introduction of this package in [[https://github.com/rudolfochrist/interleave][interleave]].

The package was modified on the top of [[github:rudolfochrist/interleave][rudolfochrist/interleave]]. The orignal interleave gets the pdf file which stored in a =INTERLEAVE_PDF= property and start. This works greatly except that you need to set the pdf path on your own. This is of inconvenience sometimes especially when you need to choose a deep or different pdf path. Addtionally, I am using [[https://github.com/jkitchin/org-ref][org-ref]] and [[https://github.com/tmalsburg/helm-bibtex][helm-bibtex]] a lot, so I modified the orignail interleave to work well with them.

* Installation

Since this is just a modified copy, I cannot sumbit it to the melpa. You can clone this package to your local storage. 

#+BEGIN_EXAMPLE
git clone https://github.com/llcc/interleave
#+END_EXAMPLE

and load it:

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "Your interleave path")
(require 'interleave)
#+END_SRC

* Usage

If you use org-ref or helm-bibtex, you should have configured your pdf and notes path, and you can make a note headline in your note file which has a property called =Custom_ID= with a bibtex entry key.
On this headline, you can start by

#+BEGIN_EXAMPLE
M-x interleave
#+END_EXAMPLE

You can find the documentation of the usage in the orignal repository. Happy noting!

